<?php

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 */
function duo_blocks_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  // Add block suggestions for custom block bundles.
  if (isset($variables['elements']['content']['#block_content'])) {
    array_splice($suggestions, 1, 0, 'block__bundle__' . $variables['elements']['content']['#block_content']->bundle());
  }
}
