<?php

/**
 * Implements hook_theme().
 */
function duo_blocks_hero_theme() {
  // Indicate that we should use template files included in this module to
  // render our block types. The templates can be overridden by a theme.
  return [
    'block__bundle__hero' => [
      'template' => 'block--bundle--hero',
      'base hook' => 'block',
    ],
  ];
}

/**
 * Implements hook_preprocess_hook().
 */
function duo_blocks_hero_preprocess_block(&$variables, $hook) {
  if (isset($variables['derivative_plugin_id']) &&
      $variables['derivative_plugin_id'] == 'hero') {
    // Though we don't define any styles for the .button class in this module,
    // let's go ahead and add that class, assuming that the front-end theme can
    // use it.
    if (isset($variables['content']['field_hero_links']['#items'])) {
      $links = $variables['content']['field_hero_links']['#items'];
      $links_count = $links->count();

      for ($i = 0; $i < $links_count; $i++) {
        $variables['content']['field_hero_links'][$i]['#options']['attributes']['class'][] = 'button';
      }      
    }
  }
}
