<?php

/**
 * @file
 * Custom code for Duo Blocks Media.
 */

/**
 * Implements hook_theme().
 */
function duo_blocks_media_theme() {
  // Indicate that we should use template files included in this module to
  // render our block types. The templates can be overridden by a theme.
  return [
    'block__bundle__media' => [
      'template' => 'block--bundle--media',
      'base hook' => 'block',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function duo_blocks_media_preprocess_media (&$variables) {
  // Add a class so that we can identify videos vs images.
  $variables['attributes']['class'][] = 'media-type-' . $variables['media']->bundle();
}
